export const currentReleaseInfo = {
  summary: "Beta 13 绕开 WindowsApps 权限陷阱，已登录的官方账号也能直接被认出来。",
  changes: [
    "续接消息写入成功后，不再被停止轮次的非关键错误误判为失败。",
    "续接首轮沿用新任务已经确认的模型配置，提升第三方渠道兼容性。",
    "续接失败时在功能区域直接显示真实原因和下一步处理建议。",
    "软件更新新增“版本说明”和“本次更新内容”两个清晰区域。",
    "设置面板增加独立滚动，窄窗口也能完整查看内容。",
    "会话续接助手明确标记为内测功能，并说明当前尚不稳定。",
    "Windows 发布版关闭多余控制台，后台系统命令不再弹出额外窗口。",
    "Windows 优先使用用户可访问的 Codex 安装路径，减少首次登录时的拒绝访问。",
    "官方登录状态兼容不同 Codex 版本的输出文案，不再只认某一种提示。",
    "macOS 与 Windows 启动后自动检查一次更新，运行期间每 3 小时检查一次。",
    "同一版本不会反复弹窗打扰；发现新版本时才推送更新提示。",
    "Windows 会逐个试运行 Codex 路径，自动跳过受保护或无权限的安装位置。",
    "同时识别 ChatGPT 与 Codex 的 Windows 商店包，以及正在运行的 Codex.exe。",
    "切换第三方渠道时保留 openai_http 官方 Provider 定义，旧官方会话可继续加载。",
    "官方渠道不再激活 openai_http，避免 ChatGPT 报 Provider not found。",
    "Windows 不再用 --version 误判 Codex，兼容更多商店版和独立安装版。",
    "优先使用 Windows App Execution Alias，并跳过无法启动的受保护 Codex 路径。",
    "ChatGPT 已登录时直接识别本地官方认证状态，不读取或回传任何令牌。",
  ],
} as const;
